version: 1.0.0-{build}
environment:
  main_project: oscript-component
  matrix:
  - ONESCRIPT_VERSION: 1.0.15
  - ONESCRIPT_VERSION: 1.0.16
  - ONESCRIPT_VERSION: 1.0.17
  - ONESCRIPT_VERSION: 1.0.18
  - ONESCRIPT_VERSION: 1.0.19
  - ONESCRIPT_VERSION: 1.0.20
  - ONESCRIPT_VERSION: 1.0.21
  - ONESCRIPT_VERSION: stable
  - ONESCRIPT_VERSION: dev
before_build:
- ps: nuget restore
init:
- REG ADD "HKLM\Software\Microsoft\Command Processor" /v Autorun /t REG_SZ /d "chcp 65001>nul" /f
- ps: Set-WinSystemLocale ru-RU
- ps: Start-Sleep -s 5
- ps: Restart-Computer
install:
- cmd: >-
    appveyor DownloadFile https://github.com/silverbulleters/ovm/releases/download/v1.0.0-RC6/ovm.exe -FileName ovm.exe

    ovm.exe install %ONESCRIPT_VERSION%

    ovm.exe use %ONESCRIPT_VERSION%

    refreshenv
    
    set PATH=%PATH%;C:\Program Files\AppVeyor\BuildAgent\

    appveyor DownloadFile https://github.com/dmpas/OneScriptDocumenter/releases/download/1.0.13/documenter.zip -FileName OneScriptDocumenter.zip
    
    7z x OneScriptDocumenter.zip > NUL

    oscript -version

    opm install opm

build:
  verbosity: minimal
configuration: Release
test_script:
- cmd: nunit3-console --x86 NUnitTests\bin\%CONFIGURATION%\NUnitTests.dll

after_build:
- cmd: >-

    del %main_project%\bin\%CONFIGURATION%\*.pdb

    mkdir bin

    OneScriptDocumenter.exe json bin\syntaxHelp.json %main_project%\bin\%CONFIGURATION%\%main_project%.dll
    
    del %main_project%\bin\%CONFIGURATION%\ScriptEngine*.* %main_project%\bin\%CONFIGURATION%\NewtonSoft*.* %main_project%\bin\%CONFIGURATION%\DotNetZip*.*
    
    xcopy %main_project%\bin\%CONFIGURATION%\* bin\

    opm build .

artifacts:
- path: .\*.ospx
  name: component
